//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annapolis.WebSite.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CircleExternalSite
    {
        public CircleExternalSite()
        {
            this.MemberUsers = new HashSet<MemberUser>();
        }
    
        public System.Guid Id { get; set; }
        public string SiteName { get; set; }
        public string SiteAddress { get; set; }
        public string Key { get; set; }
    
        public virtual ICollection<MemberUser> MemberUsers { get; set; }
    }
}
