//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annapolis.WebSite.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentComment
    {
        public ContentComment()
        {
            this.ContentVotes = new HashSet<ContentVote>();
        }
    
        public System.Guid Id { get; set; }
        public string Content { get; set; }
        public string OriginalContent { get; set; }
        public bool IsSpam { get; set; }
        public bool IsLocked { get; set; }
        public bool IsSolution { get; set; }
        public bool IsAttachedToTopic { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public System.Guid TopicId { get; set; }
        public int VoteUpCount { get; set; }
        public int VoteDownCount { get; set; }
        public System.Guid UserId { get; set; }
        public string Key { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual ContentTopic ContentTopic { get; set; }
        public virtual MemberUser MemberUser { get; set; }
        public virtual ICollection<ContentVote> ContentVotes { get; set; }
    }
}
