//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annapolis.WebSite.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentThread
    {
        public ContentThread()
        {
            this.ContentTagCategoryOnThreads = new HashSet<ContentTagCategoryOnThread>();
            this.ContentThread1 = new HashSet<ContentThread>();
            this.ContentTopics = new HashSet<ContentTopic>();
            this.PermissionOnThreads = new HashSet<PermissionOnThread>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsLocked { get; set; }
        public bool IsAbstract { get; set; }
        public bool IsDefault { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> ParentThreadId { get; set; }
        public string Key { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual ICollection<ContentTagCategoryOnThread> ContentTagCategoryOnThreads { get; set; }
        public virtual ICollection<ContentThread> ContentThread1 { get; set; }
        public virtual ContentThread ContentThread2 { get; set; }
        public virtual ICollection<ContentTopic> ContentTopics { get; set; }
        public virtual ICollection<PermissionOnThread> PermissionOnThreads { get; set; }
    }
}
