//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annapolis.WebSite.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentVote
    {
        public System.Guid Id { get; set; }
        public short Amount { get; set; }
        public System.DateTime VoteDate { get; set; }
        public System.Guid CommentId { get; set; }
        public System.Guid UserId { get; set; }
        public string Key { get; set; }
    
        public virtual ContentComment ContentComment { get; set; }
        public virtual MemberUser MemberUser { get; set; }
    }
}
