//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annapolis.WebSite.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentTag
    {
        public ContentTag()
        {
            this.ContentTag1 = new HashSet<ContentTag>();
            this.ContentTopics = new HashSet<ContentTopic>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public bool IsHot { get; set; }
        public bool IsLocked { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<System.Guid> ParentTagId { get; set; }
        public string Key { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual ICollection<ContentTag> ContentTag1 { get; set; }
        public virtual ContentTag ContentTag2 { get; set; }
        public virtual ContentTagCategory ContentTagCategory { get; set; }
        public virtual ICollection<ContentTopic> ContentTopics { get; set; }
    }
}
