//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annapolis.WebSite.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentTagCategory
    {
        public ContentTagCategory()
        {
            this.ContentTags = new HashSet<ContentTag>();
            this.ContentTagCategoryOnThreads = new HashSet<ContentTagCategoryOnThread>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public bool IsLocked { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string Key { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual ICollection<ContentTag> ContentTags { get; set; }
        public virtual ICollection<ContentTagCategoryOnThread> ContentTagCategoryOnThreads { get; set; }
    }
}
