//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annapolis.WebSite.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocaleResourceValue
    {
        public System.Guid Id { get; set; }
        public string ResourceValue { get; set; }
        public string Note { get; set; }
        public System.Guid LanguageId { get; set; }
        public System.Guid ResourceKeyId { get; set; }
        public string Key { get; set; }
    
        public virtual LocaleLanguage LocaleLanguage { get; set; }
        public virtual LocaleResourceKey LocaleResourceKey { get; set; }
    }
}
