//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annapolis.WebSite.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocaleResourceKey
    {
        public LocaleResourceKey()
        {
            this.LocaleResourceValues = new HashSet<LocaleResourceValue>();
        }
    
        public System.Guid Id { get; set; }
        public string ResourceKey { get; set; }
        public string Note { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Key { get; set; }
    
        public virtual ICollection<LocaleResourceValue> LocaleResourceValues { get; set; }
    }
}
