//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annapolis.WebSite.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocaleLanguage
    {
        public LocaleLanguage()
        {
            this.LocaleResourceValues = new HashSet<LocaleResourceValue>();
            this.Settings = new HashSet<Setting>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Culture { get; set; }
        public string LanguageImageFileName { get; set; }
        public bool RightToLeft { get; set; }
        public string Key { get; set; }
    
        public virtual ICollection<LocaleResourceValue> LocaleResourceValues { get; set; }
        public virtual ICollection<Setting> Settings { get; set; }
    }
}
