//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annapolis.WebSite.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionOnThread
    {
        public System.Guid Id { get; set; }
        public bool IsGranted { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid ThreadId { get; set; }
        public System.Guid PermissionId { get; set; }
        public string Key { get; set; }
    
        public virtual ContentThread ContentThread { get; set; }
        public virtual MemberRole MemberRole { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
