//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annapolis.WebSite.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public bool IsDefault { get; set; }
        public string HomePageController { get; set; }
        public string HomePageAction { get; set; }
        public string ForumName { get; set; }
        public string ForumUrl { get; set; }
        public bool IsClosed { get; set; }
        public string Theme { get; set; }
        public string Skin { get; set; }
        public string SMTPHost { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public string SMTPUsername { get; set; }
        public string SMTPPassword { get; set; }
        public Nullable<bool> SMTPEnableSSL { get; set; }
        public string AdminEmailAddress { get; set; }
        public bool EmailSendOnNewUser { get; set; }
        public bool EmailVerifyOnNewUser { get; set; }
        public bool EnableSocialLogins { get; set; }
        public bool AutoApproveNewMember { get; set; }
        public int TopicsPerPage { get; set; }
        public int CommentsPerPage { get; set; }
        public string DefaultTopicThumbnailFile { get; set; }
        public string UploadFileRootPath { get; set; }
        public int UpdoadFilePathHashLevel { get; set; }
        public string UploadImageFileExtension { get; set; }
        public int UploadImageFileOrginalMaxByteSize { get; set; }
        public int UploadImageFileMaxByteSize { get; set; }
        public int UploadImageFileMaxWidth { get; set; }
        public int UploadImageFileMaxHeight { get; set; }
        public string UploadDocumentFileExtension { get; set; }
        public int UploadDocumentFileMaxByteSize { get; set; }
        public string UploadFlashFileExtension { get; set; }
        public int UploadFlashFileMaxByteSize { get; set; }
        public string UploadMediaFileExtension { get; set; }
        public int UploadMediaFileMaxByteSize { get; set; }
        public string UploadThumbnailPath { get; set; }
        public int UploadThumbnailFileMaxByteSize { get; set; }
        public int UploadThumbnailWidth { get; set; }
        public int UploadThumbnailHeight { get; set; }
        public string BannedWordReplaceHolder { get; set; }
        public System.Guid SuperAdminUserId { get; set; }
        public System.Guid NewMemberStartRoleId { get; set; }
        public System.Guid LanguageId { get; set; }
        public string Key { get; set; }
    
        public virtual LocaleLanguage LocaleLanguage { get; set; }
        public virtual MemberRole MemberRole { get; set; }
        public virtual MemberUser MemberUser { get; set; }
    }
}
