//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annapolis.WebSite.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadFileCategory
    {
        public UploadFileCategory()
        {
            this.UploadFiles = new HashSet<UploadFile>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Key { get; set; }
    
        public virtual ICollection<UploadFile> UploadFiles { get; set; }
    }
}
