//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annapolis.WebSite.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadFile
    {
        public System.Guid Id { get; set; }
        public string FilePath { get; set; }
        public System.DateTime UploadDate { get; set; }
        public System.Guid CategoryId { get; set; }
        public Nullable<System.Guid> AttachId { get; set; }
        public System.Guid UserId { get; set; }
        public string Key { get; set; }
    
        public virtual MemberUser MemberUser { get; set; }
        public virtual UploadFileCategory UploadFileCategory { get; set; }
    }
}
